# Site settings {{ site.myvariable }}.
title: Tyrn Gorthad
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gorthad.cz"

# Build settings
markdown: kramdown

collections:
  articles:
    output: true
    layout: article
  officers:
    output: true

defaults:
  -
    scope:
      type: articles
    values:
      layout: article
      published: true
  -
    scope:
      type: officers
    values:
      layout: officer
      published: true
      display_order: 10

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
